In [1]:
!pip install numpy

In [2]:
import numpy as np

In [40]:
#6.Crea un array 1D con 10 valores entre 0 y 1. Redondea los decimales a 2. Obtén los elementos cuyo valor es mayor que 0.5. 
#¿En que posición/es están esos elementos?

array_6 = np.random.rand(10).round(2)
array_6

array([0.85, 0.4 , 0.4 , 0.01, 0.47, 0.82, 0.96, 0.34, 0.08, 0.83])

In [7]:
array_6_1 = np.where(array_6 > 0.5)[0]
array_6_1


array([2, 3])

In [11]:
#1.Crea un array 3D de forma (2, 3, 4) con valores aleatorios entre 1 y 100 (ambos inclusive). 
#Utiliza reshape para convertirlo en un array 2D. Deberás pensar en la forma que es correcta para hacer este cambio.

array_1_1 = np.random.randint(1, 101, (2, 3, 4))
array_1_1

array([[[61, 28, 79, 80],
        [75, 20, 94, 25],
        [25, 30, 94, 14]],

       [[74,  5, 48, 20],
        [47, 31, 53, 63],
        [97, 99, 98, 67]]])

In [12]:
array_1_2 = np.reshape(array_1_1, (-1, 4))
array_1_2

array([[61, 28, 79, 80],
       [75, 20, 94, 25],
       [25, 30, 94, 14],
       [74,  5, 48, 20],
       [47, 31, 53, 63],
       [97, 99, 98, 67]])

In [15]:
# 3. Crea un array 3D de forma (4, 3, 2) con valores aleatorios entre 0 y 1. Utiliza reshape para convertirlo en un array 2D.

array_3_1 = np.random.rand(4, 3, 2)
array_3_1

array([[[0.00753416, 0.61446984],
        [0.12731181, 0.62673192],
        [0.97776053, 0.3818351 ]],

       [[0.37419682, 0.70535051],
        [0.14393584, 0.54360323],
        [0.66044276, 0.27006632]],

       [[0.05521561, 0.27567583],
        [0.47386375, 0.68036239],
        [0.47786184, 0.11665778]],

       [[0.16529753, 0.96678184],
        [0.1182195 , 0.61642596],
        [0.10840249, 0.61377039]]])

In [19]:
array_3_2 = np.reshape(array_3_1, (-1, 4))
array_3_2

array([[0.00753416, 0.61446984, 0.12731181, 0.62673192],
       [0.97776053, 0.3818351 , 0.37419682, 0.70535051],
       [0.14393584, 0.54360323, 0.66044276, 0.27006632],
       [0.05521561, 0.27567583, 0.47386375, 0.68036239],
       [0.47786184, 0.11665778, 0.16529753, 0.96678184],
       [0.1182195 , 0.61642596, 0.10840249, 0.61377039]])

In [ ]:
# 5.Utiliza el array 3D del ejercicio 3 de reshape. 
# Utiliza transpose para cambiar el orden de los ejes y obtener un nuevo array con forma (3, 2, 4).??????

array_5_1 = np.transpose(array_3_2, (3, 2, 4))

7. ¿Y entre el transpose y el swapaxes?

TRANSPOSE: permite reordenar los ejes de un array multidimensional según una secuencia específica de ejes proporcionada como argumento
SWAPAXES: intercambia dos ejes especificados de un array multidimensional

In [32]:
array_1_1_1 = np.round(np.random.rand(2, 3, 5), 1)

In [36]:
#2. Crea un array vacío con la misma forma y dimensiones que el array creado anteriormente. 
#Vamos a reemplazar los valores de la matriz vacía que nos acabamos de crear pero basándonos 
#en los valores del primer array bajo las siguientes condiciones:

array_2_1_1 = np.empty_like(array_1_1_1, )
array_2_1_1

array([[[0.56867723, 0.83420363, 0.35085277, 0.39052135, 0.52848217],
        [0.91712272, 0.49626731, 0.21169801, 0.90414567, 0.02101046],
        [0.55403539, 0.03649714, 0.82590654, 0.1844943 , 0.94861736]],

       [[0.21385908, 0.19216421, 0.05353119, 0.21604892, 0.72850453],
        [0.06203853, 0.06877772, 0.11100816, 0.79594852, 0.41606626],
        [0.99934133, 0.48487245, 0.50406881, 0.48588546, 0.05252919]]])

In [37]:
media = np.mean(array_2_1_1)
maximo = np.max(array_2_1_1)
minimo = np.min(array_2_1_1)

In [39]:
array_2_1_2 = np.where(array_2_1_1 == media, 'A',
              np.where(array_2_1_1 > media, 'B',
              np.where(array_2_1_1 < media, 'C',
              np.where(array_2_1_1 == maximo, 'D',
              np.where(array_2_1_1 == minimo, 'E', '')))))
array_2_1_2

array([[['B', 'B', 'C', 'C', 'B'],
        ['B', 'B', 'C', 'B', 'C'],
        ['B', 'C', 'B', 'C', 'B']],

       [['C', 'C', 'C', 'C', 'B'],
        ['C', 'C', 'C', 'B', 'C'],
        ['B', 'B', 'B', 'B', 'C']]], dtype='<U1')